spring:
  application:
    name: MidPoint

  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
      file-size-threshold: 256Kb

server:
  display-name: MidPoint
  contextPath: /midpoint # Spring Boot 1.x
  session:
    timeout: 15  # in minutes. By default spring uses seconds, but tomcat/container (not embedded) uses this value
                 # as minutes - so we end up with never expiring session.
  tomcat:
    basedir: ${midpoint.home}
    max-http-post-size: 104857600 # in bytes
    
  servlet:
    path: /midpoint # Spring Boot 2.0

auth:
  logout:
    url: / # NOTE: This URL is relative to application root

#security:
#  enable-csrf: false # default for midpoint is true

# more properties with default values can be found here:
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html