os: windows
language: shell

#skips default install - see script bellow
install: true

cache:
  directories:
    - $HOME/.m2

before_install:
  - choco install maven
  - RefreshEnv.cmd
  - export MAVEN_OPTS='-Xmx6g'  
  - export JAVA_HOME=`find "/c/Program Files/Java" -name jdk1.8.*`

addons:
  hostname: localhost # workaround for short hostname

env:
  global:
    - MALLOC_ARENA_MAX=2
 
matrix:
  include:
    - name: JDK8 - Run all excluding model-intest
      script: mvn install -T 1C -q -DskipTests; mvn verify -DskipModelIntTest=true -DskipModelUnitTest=true -Dfailsafe.rerunFailingTestsCount=2
    - name: JDK8 - Run only model-intest
      script: mvn install -T 1C -q -DskipTests; mvn verify -pl :model-intest -Dfailsafe.rerunFailingTestsCount=2
