os: windows
language: shell

#skips default install - see script bellow
install: true

cache:
  directories:
    - $HOME/.m2

before_install:
  - choco install maven
  - export MAVEN_OPTS='-Xmx6g'
  - RefreshEnv.cmd
  - export JAVA_HOME=`find "/c/Program Files/Java" -name jdk1.8.*`

addons:
  hostname: localhost # workaround for short hostname

env:
  global:
    - MALLOC_ARENA_MAX=2
 
matrix:
  include:
    - name: JDK8 - Run all excluding model-intest
      script: mvn install -B -DskipTests; mvn verify -DskipModelIntTest=true  
    - name: JDK8 - Run only model-intest
      script: mvn install -B -DskipTests; mvn verify -pl :model-intest -DskipModelUnitTest=true  