os: windows
language: shell

#skips default install - see script bellow
install: true

cache:
  directories:
    - $HOME/.m2

before_install:
  - choco install maven
  - export MAVEN_OPTS='-Xmx6g'
  - RefreshEnv.cmd
  - export JAVA_HOME=`find "/c/Program Files/Java" -name jdk1.8.*`

# custom script is used so build and tests are done in one mvn command, separating it (as Travis does by default) leads to problem with ConnId (notably DummyResource)
script: mvn clean install

addons:
  hostname: localhost # workaround for short hostname